let beginnings = [
  "Hidup adalah tentang",
  "Kebahagiaan sejati datang dari",
  "Ketika kamu menghadapi tantangan, ingatlah untuk",
  "Kesuksesan lahir dari",
  "Jangan takut untuk",
  "Setiap hari adalah kesempatan untuk",
  "Keberanian adalah kunci untuk",
  "Jangan menyerah sebelum kamu",
  "Kehidupan yang bermakna adalah",
  "Ketenangan datang ketika kamu",
  "Mimpi besar dimulai dengan",
  "Hidup akan selalu berubah, jadi",
  "Keajaiban terjadi ketika kamu",
  "Bahagia bukan berarti segalanya sempurna, tetapi",
  "Hargai setiap momen karena",
  "Cinta adalah fondasi untuk",
  "Percayalah pada proses dan",
  "Kebebasan sejati ditemukan ketika kamu",
  "Jalani hidup dengan",
  "Selalu ingat untuk",
  "Keberhasilan adalah hasil dari",
  "Jangan biarkan ketakutan menghentikanmu dari",
  "Ketika kamu merasa lelah, coba",
  "Hidup bukan hanya tentang apa yang kamu miliki, tetapi",
  "Setiap langkah kecil menuju tujuan adalah",
  "Jangan remehkan kekuatan untuk",
  "Selalu ada jalan untuk",
  "Penting untuk tetap bersyukur dan",
  "Kegagalan adalah kesempatan untuk",
  "Kebijaksanaan datang dari",
  "Cobalah untuk selalu",
  "Hidup adalah perjalanan menuju",
  "Impian tidak akan menjadi kenyataan tanpa",
  "Jangan takut menghadapi tantangan, karena",
  "Kegagalan adalah bagian dari",
  "Kesabaran adalah elemen penting dalam",
  "Hidup adalah cermin dari",
  "Setiap hari adalah pelajaran tentang",
  "Hiduplah dengan penuh",
  "Temukan kedamaian dalam",
  "Tidak ada yang mustahil jika kamu",
  "Belajar dari kesalahan dan",
  "Bertumbuh setiap hari dengan",
  "Lihatlah ke depan dan",
  "Selalu ada kesempatan untuk",
  "Mulailah harimu dengan",
  "Kesuksesan dimulai dengan",
  "Setiap tantangan adalah kesempatan untuk",
  "Kekuatan datang dari",
  "Temukan kebahagiaan dalam",
  "Kesederhanaan adalah kunci untuk",
  "Jangan takut untuk bermimpi dan",
  "Tujuan hidupmu akan terwujud jika kamu",
  "Hidup yang luar biasa adalah tentang",
  "Keindahan hidup terlihat ketika kamu",
  "Keseimbangan hidup dimulai dengan",
  "Jalan menuju kebahagiaan adalah",
  "Hidup adalah kesempatan untuk",
  "Segala sesuatu yang berharga membutuhkan",
  "Kebahagiaan ditemukan dalam",
  "Jangan lupakan pentingnya",
  "Kegembiraan ditemukan ketika kamu",
  "Kunci menuju keberhasilan adalah",
  "Setiap keputusan adalah kesempatan untuk",
  "Kuatkan hatimu untuk",
  "Hidup adalah petualangan yang harus kamu",
  "Keberanian adalah langkah pertama untuk",
  "Dalam setiap masalah, ada peluang untuk",
  "Kepercayaan diri berasal dari",
  "Kebahagiaan datang ketika kamu",
  "Setiap mimpi besar dimulai dengan",
  "Perjalanan hidup akan terasa lebih ringan jika kamu",
  "Setiap kesalahan mengajarkan kita untuk",
  "Kehidupan yang indah berasal dari",
  "Kunci untuk mencapai mimpi adalah",
  "Waktu adalah teman terbaik untuk",
  "Setiap langkah dalam hidup mengajarkan kita untuk",
  "Jangan terburu-buru, nikmati setiap proses",
  "Keteguhan hati akan membawamu untuk",
  "Setiap tantangan adalah kesempatan untuk",
  "Keindahan hidup muncul ketika kamu",
  "Kebahagiaan ditemukan saat kamu",
  "Jangan pernah berhenti untuk",
  "Hidup menjadi lebih baik ketika kamu",
  "Dalam ketenangan, temukanlah",
  "Kekuatan sejati muncul saat kamu",
  "Kesederhanaan dalam hidup membawa",
  "Jangan pernah menyerah untuk",
  "Ketulusan adalah langkah pertama menuju",
  "Setiap orang memiliki kekuatan untuk",
  "Jalan menuju kesuksesan dimulai dengan",
  "Jangan takut untuk memulai lagi dan",
  "Kesuksesan adalah hasil dari keberanian untuk",
  "Perjalanan terjauh dimulai dengan",
  "Kehidupan yang penuh arti tercipta dari",
  "Ketenangan batin dimulai ketika kamu",
  "Setiap hari adalah hadiah yang harus kamu",
];

let middles = [
  "mengambil risiko dan belajar dari kegagalan.",
  "terus bekerja keras meskipun sulit.",
  "melihat peluang di tengah masalah.",
  "percaya pada dirimu sendiri dan orang lain.",
  "menghargai setiap momen, baik atau buruk.",
  "menjalani hidup dengan penuh cinta.",
  "menemukan kebahagiaan dalam hal-hal kecil.",
  "menjadi dirimu sendiri tanpa takut dihakimi.",
  "menerima kekurangan dan berusaha lebih baik.",
  "tetap teguh meskipun banyak rintangan.",
  "membantu orang lain dalam kesulitan.",
  "membuka hati untuk hal-hal baru.",
  "mengubah rintangan menjadi peluang.",
  "menerima diri sendiri dengan segala kelebihan dan kekurangan.",
  "mengatasi ketakutan dengan keberanian.",
  "belajar dari masa lalu untuk masa depan yang lebih baik.",
  "menghargai waktu yang ada.",
  "menerima perubahan dengan tangan terbuka.",
  "tetap positif dalam segala keadaan.",
  "mencari makna dalam setiap pengalaman.",
  "melangkah maju meskipun tidak ada kepastian.",
  "memperjuangkan apa yang kamu yakini.",
  "menemukan kekuatan dalam kelemahan.",
  "merangkul tantangan sebagai kesempatan untuk tumbuh.",
  "menerima kehidupan apa adanya.",
  "berusaha keras mencapai tujuan yang lebih tinggi.",
  "mendengarkan hati dan intuisi.",
  "menghadapi setiap hari dengan rasa syukur.",
  "mencari kebahagiaan di tengah kesederhanaan.",
  "menemukan kedamaian dalam diri sendiri.",
  "berbagi kebaikan dengan orang lain.",
  "membuka diri untuk cinta dan kasih sayang.",
  "mengubah mimpi menjadi kenyataan dengan tindakan.",
  "bersyukur atas hal-hal kecil yang ada di sekitar.",
  "menemukan kebahagiaan dalam berbagi.",
  "menghadapi ketakutan dengan kepala tegak.",
  "menghormati diri sendiri dan orang lain.",
  "menjaga keseimbangan antara kerja dan istirahat.",
  "mempercayai bahwa segalanya akan baik-baik saja.",
  "membiarkan cinta membimbing setiap langkah.",
  "berani bermimpi dan mengambil tindakan.",
  "menjalani hidup dengan penuh keyakinan.",
  "melihat setiap kegagalan sebagai pelajaran.",
  "menghargai perbedaan dan keberagaman.",
  "menerima kenyataan dan berusaha lebih baik.",
  "melakukan kebaikan tanpa mengharapkan balasan.",
  "berdiri teguh di tengah badai.",
  "memanfaatkan setiap kesempatan yang ada.",
  "merayakan setiap pencapaian, besar atau kecil.",
  "mendengarkan suara hati tanpa ragu.",
  "terus belajar dan tumbuh setiap hari.",
  "berusaha mencapai keseimbangan dalam hidup.",
  "menemukan kekuatan dalam kerendahan hati.",
  "menghadapi setiap hari dengan harapan baru.",
  "menggunakan waktu dengan bijak.",
  "menghargai apa yang sudah kamu miliki.",
  "mengambil keputusan yang bijaksana dalam hidup.",
  "mengubah mimpi menjadi kenyataan.",
  "menghadapi hidup dengan semangat pantang menyerah.",
  "melihat setiap hari sebagai kesempatan baru.",
  "menghargai keindahan di sekitarmu.",
  "menjaga hati tetap terbuka untuk hal-hal baik.",
  "mengambil setiap kesempatan untuk belajar.",
  "memahami bahwa kebahagiaan adalah pilihan.",
  "menemukan cinta dan kebahagiaan dalam diri sendiri.",
  "melihat setiap tantangan sebagai peluang.",
  "tetap fokus pada tujuan jangka panjang.",
  "membangun hubungan yang mendukung.",
  "memperjuangkan apa yang benar dalam hidup.",
  "tetap rendah hati meskipun sukses.",
  "mencari kebenaran dan kejujuran.",
  "memanfaatkan waktu sebaik-baiknya.",
  "mengubah kelemahan menjadi kekuatan.",
  "berpikir positif meskipun keadaan sulit.",
  "berusaha keras mencapai mimpi yang besar.",
  "berani mengambil langkah pertama.",
  "memahami bahwa segalanya memiliki alasan.",
  "berusaha mencapai tujuan dengan tekad kuat.",
  "melakukan hal-hal kecil dengan cinta.",
  "menemukan kebahagiaan dalam perjalanan, bukan tujuan.",
  "berusaha menjadi versi terbaik dari dirimu.",
  "menghadapi hidup dengan sikap penuh syukur.",
  "menyadari bahwa setiap hari adalah berkah.",
  "membangun masa depan dengan kerja keras hari ini.",
  "menghadapi setiap tantangan dengan senyuman.",
  "menerima hidup dengan segala keindahannya.",
  "menjalani hari dengan penuh cinta dan kebaikan.",
];

let endings = [
  "Karena hidup hanya sekali.",
  "Kamu akan tumbuh lebih kuat setiap hari.",
  "Hal-hal baik datang kepada mereka yang sabar.",
  "Setiap langkah maju adalah kemenangan.",
  "Jadilah inspirasi bagi dirimu dan orang lain.",
  "Kebahagiaan sejati dimulai dari diri sendiri.",
  "Hidupmu berharga, jangan sia-siakan.",
  "Kesuksesan adalah perjalanan, bukan tujuan akhir.",
  "Segalanya akan menjadi lebih baik pada akhirnya.",
  "Jangan pernah berhenti belajar.",
  "Hargai setiap momen dalam perjalananmu.",
  "Kamu lebih kuat dari yang kamu kira.",
  "Tantangan akan membentukmu menjadi lebih baik.",
  "Kebahagiaan datang dari ketenangan batin.",
  "Tidak ada yang tidak mungkin jika kamu percaya.",
  "Jadilah perubahan yang kamu inginkan di dunia.",
  "Setiap hari adalah kesempatan untuk tumbuh.",
  "Percayalah, segala sesuatu terjadi untuk sebuah alasan.",
  "Bersyukurlah atas semua yang kamu miliki.",
  "Tetap rendah hati dan bersyukur.",
  "Kehidupan adalah tentang memberi dan menerima.",
  "Ketenangan pikiran adalah kunci kebahagiaan.",
  "Kamu memiliki kekuatan untuk mengubah hidupmu.",
  "Selalu ada harapan selama kamu tidak menyerah.",
  "Jangan takut untuk bermimpi besar.",
  "Sabar adalah kunci untuk mencapai kebahagiaan.",
  "Cintai dirimu sendiri terlebih dahulu.",
  "Kebaikan akan selalu kembali padamu.",
  "Tetap semangat meskipun jalan terasa sulit.",
  "Kamu tidak sendiri, selalu ada seseorang yang peduli.",
  "Keberhasilan dimulai dari langkah kecil.",
  "Setiap hari adalah peluang untuk memulai dari awal.",
  "Ciptakan kebahagiaanmu sendiri.",
  "Jangan biarkan kegagalan menghentikanmu.",
  "Setiap usaha yang kamu lakukan akan membuahkan hasil.",
  "Hidup adalah tentang menemukan keseimbangan.",
  "Tidak ada jalan pintas menuju kesuksesan.",
  "Bersikap baiklah pada dirimu sendiri dan orang lain.",
  "Kamu adalah arsitek hidupmu sendiri.",
  "Jangan pernah menyerah pada impianmu.",
  "Bekerjalah dengan keras dan dengan hati.",
  "Kegagalan adalah bagian dari proses belajar.",
  "Bersyukur adalah jalan menuju kebahagiaan.",
  "Kamu mampu melakukan hal-hal luar biasa.",
  "Jalani hidupmu dengan penuh cinta dan keyakinan.",
  "Setiap hari adalah kesempatan baru untuk sukses.",
  "Kebahagiaan datang dari dalam diri.",
  "Jangan takut untuk mencoba sesuatu yang baru.",
  "Keberanian adalah kunci kesuksesan.",
  "Kehidupan yang penuh makna adalah kehidupan yang dijalani dengan hati.",
  "Jangan menyerah, karena setiap hari adalah kesempatan baru.",
  "Kamu berhak mendapatkan yang terbaik dalam hidup.",
  "Setiap mimpi besar membutuhkan kerja keras.",
  "Jangan terburu-buru, nikmati prosesnya.",
  "Hidup adalah petualangan yang harus dijalani sepenuh hati.",
  "Hargai dirimu sendiri dan perjalananmu.",
  "Tersenyumlah, karena hidup ini berharga.",
  "Segala hal yang berharga memerlukan waktu dan usaha.",
  "Jangan takut akan perubahan, karena itu adalah bagian dari pertumbuhan.",
  "Berbaik hatilah, karena dunia membutuhkan lebih banyak cinta.",
  "Kegigihan adalah kunci menuju kesuksesan.",
  "Kehidupan yang penuh kasih adalah kehidupan yang bermakna.",
  "Tidak ada yang mustahil jika kamu berusaha.",
  "Jangan pernah berhenti mengejar mimpimu.",
  "Ketenangan batin adalah kekayaan yang sesungguhnya.",
  "Keindahan hidup terlihat ketika kamu bersyukur.",
  "Bermimpilah, beranilah, dan capailah.",
  "Jangan takut pada kegagalan, karena itu adalah batu loncatan menuju kesuksesan.",
  "Kamu memiliki kekuatan untuk mengubah dunia.",
  "Setiap tantangan adalah kesempatan untuk tumbuh.",
  "Jangan biarkan ketakutan menghentikanmu dari mencapai yang kamu inginkan.",
  "Cintai dan hargai dirimu sendiri.",
  "Kamu berharga lebih dari yang kamu kira.",
  "Hidup adalah tentang mencintai, berbagi, dan memberi.",
  "Setiap hari adalah kesempatan baru untuk membuat perbedaan.",
  "Kamu adalah penulis cerita hidupmu sendiri.",
  "Percayalah bahwa segalanya akan baik-baik saja.",
  "Setiap langkah menuju impianmu adalah kemenangan.",
  "Kehidupan yang dijalani dengan cinta adalah kehidupan yang bermakna.",
  "Jangan takut untuk gagal, karena itu bagian dari proses.",
];
function randomizerVar() {
  lifeQuote = `${beginnings[Math.floor(Math.random() * beginnings.length)]} ${
    middles[Math.floor(Math.random() * middles.length)]
  } ${endings[Math.floor(Math.random() * endings.length)]}`;

  document.getElementById("quote").textContent = lifeQuote;
}

function copy() {
  if (lifeQuote !== "") {
    navigator.clipboard
      .writeText(lifeQuote)
      .then(function () {
        Swal.fire({
          position: "top-end",
          icon: "success",
          title: "Copied",
          showConfirmButton: false,
          timer: 1500,
        });
      })
      .catch(function (err) {
        console.error("Gagal menyalin teks: ", err);
      });
  } else {
    alert("Tidak ada teks yang dapat disalin!");
  }
}

console.log('All work')
